BEGIN TRANSACTION;
CREATE TABLE model_texture (
                    title_name TEXT NOT NULL,
                    model_path TEXT NOT NULL,
                    texture_path TEXT NOT NULL,
                    PRIMARY KEY (title_name, model_path),
                    FOREIGN KEY(title_name) REFERENCES title(name)
                    );
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_barrel_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_barrel_02.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_battleship_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_cargo_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_cont_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_cont_02.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_cruiser_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_fighter_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_hangar.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/alien_weapon_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/asteroid.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/asteroid_still.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/cargo_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/doc_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/drone.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/explo.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/explobig.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/feknor_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/hull.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/mine.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/mine_explo.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/mine_no_ani.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/photon1.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/photon2.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/photon3.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/pirate_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/protagonist_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/protagonist_02.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/protagonist_03.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/protagonist_04.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/schrott.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/shield.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/skybox.mbac','data/textures/stars.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_barrel_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_barrel_02.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_battleship_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_bot.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_cargo_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_cont_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_cont_02.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_cruiser_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_fighter_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_hangar.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_lights.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/terran_weapon_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Galaxy on Fire','data/3d/vlad_01.mbac','data/textures/ships.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Asphalt1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Asphalt2_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Barrel1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Barrel2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Box1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Box2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','CBlock1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','CFence1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','CFence2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','ConcreteSlabs1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','ConcreteTube1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Corridor1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Door1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Door2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','DoorStud1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','DoorStud2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Fire1_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Forest1_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','ForestClearing1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','ForestClearing2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','ForestWall1_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','ForestWall2_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','GrassPlot1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','GrassPlot2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','GreenAcid1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuild1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuild2_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuild3_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuild4_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuild5_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuild6_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuildA1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuildA2_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuildA3_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuildB1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryBuildB2_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','IndustryTube1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Lamp1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Lamp2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Lamp3_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','LampGlare1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','MetalCase1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','MetalGate1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','MetalRVent1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','RailRoad1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','RedGlare_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Rock1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Room1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Room2_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Rubbish1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','SelskiyDom1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','SewerSectionC_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','SewerSectionI_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','SewerSectionT_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','SewerWallBlind1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Sky1_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Sky2_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Sky3_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Stone1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Stone2_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Storage1_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Storage2_00.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Tree1_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Tree2_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Tree3_00.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','TreeOld1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','UAZ1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','WFence1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','WFence2_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','Window1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','WindowSill1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','WoodPanel1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','WoodReel1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','WoodTable1_00.mbac','t1.bmp');
INSERT INTO "model_texture" VALUES('Stalker','flash.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','pers_bandit.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','pers_killer.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','pers_soldier.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','pers_stalker.mbac','t3.bmp');
INSERT INTO "model_texture" VALUES('Stalker','weap_AK74.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','weap_groza.mbac','t2.bmp');
INSERT INTO "model_texture" VALUES('Stalker','weap_l85.mbac','t2.bmp');
CREATE TABLE title (
                    name TEXT NOT NULL PRIMARY KEY,
                    model_axis_forward TEXT,
                    model_axis_up TEXT
                    );
INSERT INTO "title" VALUES('Galaxy on Fire','-Z','Y');
INSERT INTO "title" VALUES('Stalker','X','Z');
COMMIT;
